import { Destination } from "./types";

export const destinations: Destination[] = [
    {
        name: "Miami, FL",
        vibes: { beach: 5, city: 4, nature: 2, culture: 3, relaxation: 4, nightlife: 5, adventure: 3 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 180,
        dietary_friendly: ["vegetarian", "vegan", "halal", "gluten-free"],
        best_for: ["beach lovers", "nightlife", "food scene", "water sports"],
        highlights: ["South Beach", "Wynwood Walls", "Everglades day trip", "Little Havana", "Key Biscayne"],
        weather_note: "Hot year-round, hurricane season Jun-Nov",
        walkability: "moderate",
        transit: "limited",
    },
    {
        name: "San Diego, CA",
        vibes: { beach: 5, city: 3, nature: 4, culture: 3, relaxation: 4, nightlife: 3, adventure: 4 },
        budget_level: "mid",
        avg_daily_cost_pp: 160,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["beaches", "outdoor activities", "zoo/wildlife", "craft beer", "mild weather"],
        highlights: ["La Jolla Cove", "Balboa Park", "San Diego Zoo", "Gaslamp Quarter", "Torrey Pines"],
        weather_note: "Mild year-round, perfect 65-80F",
        walkability: "moderate",
        transit: "moderate",
    },
    {
        name: "New York City, NY",
        vibes: { beach: 1, city: 5, nature: 1, culture: 5, relaxation: 1, nightlife: 5, adventure: 2 },
        budget_level: "high",
        avg_daily_cost_pp: 250,
        dietary_friendly: ["vegetarian", "vegan", "halal", "kosher", "gluten-free", "nut-free", "dairy-free"],
        best_for: ["culture", "food", "shopping", "nightlife", "art", "theater"],
        highlights: ["Central Park", "MET Museum", "Broadway", "Brooklyn Bridge", "Times Square"],
        weather_note: "Hot summers, cold winters, best in spring/fall",
        walkability: "excellent",
        transit: "excellent",
    },
    {
        name: "Savannah, GA",
        vibes: { beach: 3, city: 3, nature: 3, culture: 5, relaxation: 4, nightlife: 3, adventure: 2 },
        budget_level: "mid",
        avg_daily_cost_pp: 130,
        dietary_friendly: ["vegetarian", "gluten-free"],
        best_for: ["history buffs", "southern charm", "architecture", "food", "ghost tours"],
        highlights: ["Forsyth Park", "River Street", "Tybee Island", "Bonaventure Cemetery", "Historic District"],
        weather_note: "Hot humid summers, mild winters",
        walkability: "excellent",
        transit: "limited",
    },
    {
        name: "Austin, TX",
        vibes: { beach: 1, city: 4, nature: 3, culture: 4, relaxation: 3, nightlife: 5, adventure: 3 },
        budget_level: "mid",
        avg_daily_cost_pp: 150,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["live music", "food trucks", "nightlife", "tech culture", "outdoor swimming"],
        highlights: ["6th Street", "Barton Springs", "Lady Bird Lake", "South Congress", "BBQ trail"],
        weather_note: "Hot summers (100F+), mild winters",
        walkability: "moderate",
        transit: "limited",
    },
    {
        name: "Denver, CO",
        vibes: { beach: 0, city: 3, nature: 5, culture: 3, relaxation: 3, nightlife: 3, adventure: 5 },
        budget_level: "mid",
        avg_daily_cost_pp: 155,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["hiking", "mountains", "craft beer", "skiing nearby", "outdoor adventures"],
        highlights: ["Rocky Mountain NP", "Red Rocks", "RiNo Art District", "Coors Brewery", "Garden of the Gods"],
        weather_note: "300 days of sunshine, cold winters, dry climate",
        walkability: "moderate",
        transit: "moderate",
    },
    {
        name: "New Orleans, LA",
        vibes: { beach: 1, city: 4, nature: 2, culture: 5, relaxation: 3, nightlife: 5, adventure: 2 },
        budget_level: "mid",
        avg_daily_cost_pp: 145,
        dietary_friendly: ["vegetarian", "gluten-free"],
        best_for: ["food", "music", "culture", "history", "nightlife", "unique experiences"],
        highlights: ["French Quarter", "Bourbon Street", "Garden District", "Swamp tours", "Jazz clubs"],
        weather_note: "Hot humid summers, mild winters, rain common",
        walkability: "good (French Quarter)",
        transit: "moderate",
    },
    {
        name: "Nashville, TN",
        vibes: { beach: 0, city: 3, nature: 2, culture: 4, relaxation: 3, nightlife: 5, adventure: 2 },
        budget_level: "mid",
        avg_daily_cost_pp: 140,
        dietary_friendly: ["vegetarian", "gluten-free"],
        best_for: ["music lovers", "food", "nightlife", "bachelorette trips", "southern culture"],
        highlights: ["Broadway honky-tonks", "Grand Ole Opry", "Hot chicken trail", "Ryman Auditorium", "The Gulch"],
        weather_note: "Hot summers, mild winters",
        walkability: "moderate (downtown)",
        transit: "limited",
    },
    {
        name: "San Francisco, CA",
        vibes: { beach: 2, city: 5, nature: 3, culture: 5, relaxation: 2, nightlife: 3, adventure: 3 },
        budget_level: "high",
        avg_daily_cost_pp: 220,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free", "halal"],
        best_for: ["culture", "tech scene", "food diversity", "iconic landmarks", "unique neighborhoods"],
        highlights: ["Golden Gate Bridge", "Alcatraz", "Chinatown", "Fisherman's Wharf", "Muir Woods"],
        weather_note: "Cool year-round (50-70F), foggy summers",
        walkability: "good",
        transit: "excellent",
    },
    {
        name: "Sedona, AZ",
        vibes: { beach: 0, city: 1, nature: 5, culture: 3, relaxation: 5, nightlife: 1, adventure: 4 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 170,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["nature lovers", "spiritual retreats", "hiking", "photography", "wellness"],
        highlights: ["Red Rock formations", "Cathedral Rock", "Vortex sites", "Tlaquepaque Arts", "Slide Rock SP"],
        weather_note: "Warm and dry, best in spring/fall",
        walkability: "low (car needed)",
        transit: "none",
    },
    {
        name: "Charleston, SC",
        vibes: { beach: 4, city: 3, nature: 3, culture: 5, relaxation: 4, nightlife: 3, adventure: 2 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 165,
        dietary_friendly: ["vegetarian", "gluten-free"],
        best_for: ["history", "southern food", "architecture", "beach access", "romance"],
        highlights: ["Rainbow Row", "Fort Sumter", "Folly Beach", "King Street", "Magnolia Plantation"],
        weather_note: "Hot humid summers, mild winters",
        walkability: "excellent (downtown)",
        transit: "limited",
    },
    {
        name: "Seattle, WA",
        vibes: { beach: 1, city: 4, nature: 4, culture: 4, relaxation: 3, nightlife: 3, adventure: 3 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 185,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["coffee culture", "tech scene", "nature nearby", "seafood", "music history"],
        highlights: ["Pike Place Market", "Space Needle", "Mount Rainier", "Chihuly Garden", "Museum of Pop Culture"],
        weather_note: "Rainy fall-spring, gorgeous dry summers",
        walkability: "good",
        transit: "good",
    },
    {
        name: "Honolulu, HI",
        vibes: { beach: 5, city: 3, nature: 5, culture: 3, relaxation: 5, nightlife: 2, adventure: 4 },
        budget_level: "high",
        avg_daily_cost_pp: 230,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["beaches", "nature", "relaxation", "snorkeling", "hiking", "sunsets"],
        highlights: ["Waikiki Beach", "Diamond Head", "North Shore", "Pearl Harbor", "Hanauma Bay"],
        weather_note: "Warm year-round (75-85F), brief rain showers",
        walkability: "moderate (Waikiki)",
        transit: "moderate",
    },
    {
        name: "Portland, OR",
        vibes: { beach: 1, city: 3, nature: 4, culture: 4, relaxation: 3, nightlife: 3, adventure: 3 },
        budget_level: "mid",
        avg_daily_cost_pp: 145,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free", "dairy-free"],
        best_for: ["foodies", "craft beer/coffee", "quirky culture", "nature nearby", "no sales tax shopping"],
        highlights: ["Powell's Books", "Food cart pods", "Forest Park", "Columbia Gorge", "Alberta Arts District"],
        weather_note: "Rainy Oct-May, perfect dry summers",
        walkability: "good",
        transit: "good",
    },
    {
        name: "Las Vegas, NV",
        vibes: { beach: 0, city: 4, nature: 2, culture: 2, relaxation: 3, nightlife: 5, adventure: 3 },
        budget_level: "variable",
        avg_daily_cost_pp: 175,
        dietary_friendly: ["vegetarian", "vegan", "halal", "kosher", "gluten-free"],
        best_for: ["nightlife", "entertainment", "shows", "food buffets", "day trips to Grand Canyon/Red Rock"],
        highlights: ["The Strip", "Fremont Street", "Red Rock Canyon", "Shows/Cirque", "Grand Canyon day trip"],
        weather_note: "Extremely hot summers (110F+), mild winters",
        walkability: "moderate (Strip only)",
        transit: "limited",
    },
    {
        name: "Asheville, NC",
        vibes: { beach: 0, city: 2, nature: 5, culture: 4, relaxation: 4, nightlife: 2, adventure: 3 },
        budget_level: "mid",
        avg_daily_cost_pp: 135,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["nature lovers", "craft beer", "art scene", "Blue Ridge mountains", "farm-to-table food"],
        highlights: ["Blue Ridge Parkway", "Biltmore Estate", "River Arts District", "Brewery trail", "Great Smoky Mountains"],
        weather_note: "Four seasons, cool mountain climate",
        walkability: "good (downtown)",
        transit: "limited",
    },
    {
        name: "Maui, HI",
        vibes: { beach: 5, city: 1, nature: 5, culture: 3, relaxation: 5, nightlife: 1, adventure: 5 },
        budget_level: "high",
        avg_daily_cost_pp: 250,
        dietary_friendly: ["vegetarian", "vegan", "gluten-free"],
        best_for: ["beaches", "road trips", "snorkeling", "whale watching", "sunrises", "tropical nature"],
        highlights: ["Road to Hana", "Haleakala sunrise", "Molokini snorkeling", "Ka'anapali Beach", "Lahaina"],
        weather_note: "Warm year-round, microclimates vary by coast",
        walkability: "low (car essential)",
        transit: "very limited",
    },
    {
        name: "Washington, DC",
        vibes: { beach: 0, city: 4, nature: 2, culture: 5, relaxation: 2, nightlife: 3, adventure: 1 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 175,
        dietary_friendly: ["vegetarian", "vegan", "halal", "kosher", "gluten-free"],
        best_for: ["history", "museums (free!)", "politics", "culture", "cherry blossoms"],
        highlights: ["Smithsonian museums", "National Mall", "Georgetown", "Lincoln Memorial", "Library of Congress"],
        weather_note: "Hot humid summers, cold winters, best in spring",
        walkability: "excellent",
        transit: "excellent (Metro)",
    },
    {
        name: "Yellowstone/Jackson Hole, WY",
        vibes: { beach: 0, city: 0, nature: 5, culture: 1, relaxation: 3, nightlife: 1, adventure: 5 },
        budget_level: "mid-high",
        avg_daily_cost_pp: 180,
        dietary_friendly: ["vegetarian", "gluten-free"],
        best_for: ["nature purists", "wildlife", "hiking", "geothermal wonders", "photography"],
        highlights: ["Old Faithful", "Grand Prismatic Spring", "Grand Teton NP", "Wildlife safaris", "Lamar Valley"],
        weather_note: "Short summer season (Jun-Sep), very cold otherwise",
        walkability: "none (car required)",
        transit: "none",
    },
    {
        name: "Chicago, IL",
        vibes: { beach: 2, city: 5, nature: 2, culture: 5, relaxation: 2, nightlife: 4, adventure: 2 },
        budget_level: "mid",
        avg_daily_cost_pp: 165,
        dietary_friendly: ["vegetarian", "vegan", "halal", "gluten-free"],
        best_for: ["architecture", "deep-dish pizza", "museums", "comedy shows", "lakefront"],
        highlights: ["Millennium Park", "Art Institute", "Willis Tower", "Navy Pier", "Wrigley Field"],
        weather_note: "Brutally cold winters, warm summers with lakefront breeze",
        walkability: "excellent",
        transit: "excellent (L train)",
    },
];
